name: ci-pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: jay-withers/workflows/.github/workflows/pre-commit.yml@6599cdd2b3f2870119a2de439360471b2b94765e # v1.4.11
    with:
      terraform: true
