name: ci-pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: jay-withers/workflows/.github/workflows/pre-commit.yml@9034ae4e79d7da4f88ca804e8a97c679d5cec47a # v1.0.1
    with:
      terraform: true
